### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by motono-sa** [motono-sa/Youru_tra#65]
## サービス名
Youるトレ

## サービスURL
https://youru-tra.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 筋トレの部位検索機能：鍛えたい部位を１箇所検索する機能。 
　ランダムに3件の動画が表示される（検索例：腕、胸部、背中、お腹、脚）
- [x] 動画表示機能：youtubeから取得した動画を表示。
- [x] ユーザー登録：メールアドレス、名前など登録

## READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください
- [x] 筋トレの部位検索機能：
　部位を「腕、胸部、背中、お腹、脚、全身」の中から1つ選択して動画の検索が可能。

- [x] 動画表示機能：youtubeから取得した動画を表示
　検索されたタイトルを表示して、クリックしたら動画表示ページへ移動が可能。

- [x] ユーザー登録：名前、メールアドレス、パスワードの登録
　ユーザーの登録が可能（名前、メールアドレス、パスワード）
　ユーザーの編集が可能（名前、メールアドレス）

## READMEレビュー時から変更した機能
- [x] 筋トレの部位検索機能に関して
動画の表示件数を1件に変更。
鍛えたい部位の選択に「全身」を追加。

## サービスイメージがわかるようなスクリーンショット等
マイページ関係の画面
https://gyazo.com/622250573ea90fd39ae2a0082de14026

動画検索関係の画面
https://gyazo.com/71d1ff4931d926bb452a1d91124a5a20

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
